# Generated by Django 3.2.20 on 2023-08-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_filter',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Adidas', 'Adidas'), ('Nike', 'Nike'), ('Saucony', 'Saucony'), ('Brooks', 'Brooks'), ('On', 'On'), ('Asics', 'Asics')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=254),
        ),
    ]
