# Generated by Django 3.2.20 on 2023-11-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230830_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/banner_rzae6b', upload_to='images/'),
        ),
    ]
