# Generated by Django 3.2.20 on 2023-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../blank-profile-picture-973460_1280_fxozyw', upload_to='images'),
        ),
    ]
