# Generated by Django 3.2.20 on 2023-11-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/blank-profile-image_ztb3iv', upload_to='images/'),
        ),
    ]
